apiVersion: batch/v1
kind: Job
metadata:
  name: restore-longhorn-volume-job
spec:
  template:
    metadata:
      name: restore-longhorn-volume-job
    spec:
      containers:
      - name: restore-longhorn-volume-job
        image: sekhrivijay/restore-longhorn-volume-job:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: true
        env:
        - name: FROM_VOLUME_NAME
          value: test
        - name: FROM_SNAPSHOT_NAME
          value: backup-c-d9c77a51
        - name: TO_VOLUME_NAME
          value: test3
        - name: TO_PV_NAME
          value: new-pv3
        - name: TO_PVC_NAME
          value: new-pvc3
        - name: NAMESPACE
          value: test

        resources:
          requests:
            memory: "0.5Gi"
            cpu: 500m
          limits:
            memory: "4.0Gi"
            cpu: 2000m
      restartPolicy: Never
  backoffLimit: 4
